name: Terraform simple deploy

permissions:
  id-token: write
  contents: read
  
on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: LAPTOP-4TIMG3M8

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: latest

    - name: Azure Login
      uses: Azure/login@v2
      with:
        client-id: ${{ secrets.APPLICATION_CLIENT_ID }}
        tenant-id: ${{ secrets.DIRECTORY_TENANT_ID }}
        subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

    - name: Terraform Init
      working-directory: env/dev
      run: terraform init

    - name: Terraform Plan
      working-directory: env/dev
      run: terraform plan

    - name: Terraform Apply
      working-directory: env/dev
      run: terraform apply -auto-approve
