name: Terraform deploy on azure-repo

permissions:
  id-token: write
  contents: read
  
on:
  pull_request:
    branches:
     - main
  push:
    branches:
     - main

jobs:
  terraform:
    name: 'terraform init-plan-apply'
    runs-on: LAPTOP-4TIMG3M8

    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
    
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
      with:
        terraform_version: latest
        
    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        client-id: ${{ secrets.APPLICATION_CLIENT_ID }}
        tenant-id: ${{ secrets.DIRECTORY_TENANT_ID }}
        subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

    - name: terraform init
      working-directory: env/dev
      run: terraform init -upgrade

    # - name: terraform fmt
    #   working-directory: env/dev
    #   run: terraform fmt

    - name: terraform validate
      working-directory: env/dev
      run: terraform validate

    - name: terraform plan
      working-directory: env/dev
      run: terraform plan

    - name: terraform apply
      working-directory: env/dev
      run: terraform apply --auto-approve
