name: Terraform deploy on azure-repo

permissions:
  id-token: write
  contents: read
  
on:
  pull_request:
    branches:
     - main
  push:
    branches:
     - main

jobs:
  terraform-init-plan:
    name: 'terraform init-plan'
    runs-on: LAPTOP-4TIMG3M8
    if: github.event_name =='pull_request'

    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
    
    - name: Install Terraform
      uses: little-core-labs/install-terraform@v2.0.0
      with:
        version: latest
        
    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        client-id: ${{ secrets.APPLICATION_CLIENT_ID }}
        tenant-id: ${{ secrets.DIRECTORY_TENANT_ID }}
        subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

    - name: terraform init
      working-directory: env/dev
      run: terraform init 

    - name: terraform fmt
      working-directory: env/dev
      run: terraform fmt 

    - name: terraform validate
      working-directory: env/dev
      run: terraform validate

    - name: terraform plan
      working-directory: env/dev
      run: terraform plan

  terraform-apply:
    name: terraform apply
    runs-on: LAPTOP-4TIMG3M8
    if: github.event_name =='push' && github.ref == 'refs/heads/main'

    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
    
    - name: Install Terraform
      uses: little-core-labs/install-terraform@v2.0.0
      with:
        version: latest
        
    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        client-id: ${{ secrets.APPLICATION_CLIENT_ID }}
        tenant-id: ${{ secrets.DIRECTORY_TENANT_ID }}
        subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

    - name: terraform init
      working-directory: env/dev
      run: terraform init 
    
    - name: terraform apply
      working-directory: env/dev
      run: terraform apply --auto-approve
